CREATE TABLE IF NOT EXISTS USERS
(
  ID UUID PRIMARY KEY DEFAULT (uuid_generate_v1()),
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  FIRST_NAME VARCHAR(255),/* NOT NULL,*/
  LAST_NAME VARCHAR(255),/* NOT NULL,*/
  DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GAMES
(
  ID UUID PRIMARY KEY DEFAULT (uuid_generate_v1()),
  NAME VARCHAR(255) NOT NULL
);